# Generated by Django 4.2.5 on 2023-12-23 08:25

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=chat.models.profile_media_path
            ),
        ),
    ]
